### ISSUE TITLE
Only 6 top genes not 10

### ISSUE THREAD

**Issue by mschulz789** [Dragonmasterx87/CompBio1-Tulane#4]
Hello! 
I was trying to get the top 10 DEGs, however, my result was only coming up with 6 DEGs.

`# Find differentially expressed features between CTRL and STIM DCs
dc.de.markers <- FindMarkers(pbmc, ident.1 = "DC_STIM", ident.2 = "DC_CTRL")
# view results
head(dc.de.markers)`

**Comment by Dragonmasterx87** [comment]
Hi @mschulz789 !

Thanks for asking here. It seems you are missing the output of `head(dc.de.markers)` can you paste the output please?

**Comment by Dragonmasterx87** [comment]
This issue is now marked as completed and closed if you have another issue please reopen or create a new issue. Thanks.
