### ISSUE TITLE
Problem with integrating data 

### ISSUE THREAD

**Issue by Depraved-Dolphin** [Dragonmasterx87/CompBio1-Tulane#6]
My graph output does not split the experimental and control groups into separate violin plots. Look at the graph and see that the violin plots do not contain two columns or violins, as the experimental and control groups are plotted as one using the same color. I need help splitting the graph.

![image](https://github.com/Dragonmasterx87/CompBio1-Tulane/assets/142049606/9ff277ba-ae17-4f76-8b48-2de5c9621978)

Here is the code leading up to this point:

`suppressPackageStartupMessages({
  library(dplyr)
  library(Rcpp)
  library(harmony)
  library(Seurat)
  library(patchwork)
  library(SeuratData)
  library(qs)
  library(ggplot2)
})

{
  ctrl.d1.data <- Read10X(data.dir = r"(C:\Users\cellsworth\Documents\R data\SC_data\B6_2dpi_F1_filtered_feature_bc_matrix)")
  ctrl.d1 <- CreateSeuratObject(counts = ctrl.d1.data, project = "C3.now", min.cells = 3, min.features = 200)
  ctrl.d2.data <- Read10X(data.dir = r"(C:\Users\cellsworth\Documents\R data\SC_data\B6_2dpi_F2_filtered_feature_bc_matrix)")
  ctrl.d2 <- CreateSeuratObject(counts = ctrl.d2.data, project = "C3.now", min.cells = 3, min.features = 200)
  
  stim.d1.data <- Read10X(data.dir = r"(C:\Users\cellsworth\Documents\R data\SC_data\C3KO_F1_filtered_feature_bc_matrix)")
  stim.d1 <- CreateSeuratObject(counts = stim.d1.data, project = "C3.now", min.cells = 3, min.features = 200)
  stim.d2.data <- Read10X(data.dir = r"(C:\Users\cellsworth\Documents\R data\SC_data\C3KO_F2_filtered_feature_bc_matrix)")
  stim.d2 <- CreateSeuratObject(counts = stim.d2.data, project = "C3.now", min.cells = 3, min.features = 200)
}

# If you are just loading data from your saved file and dont have a saved ifnb.list object
ctrl.d1$donor <- "d1"
ctrl.d2$donor <- "d2"

stim.d1$donor <- "d1"
stim.d2$donor <- "d2"

ifnb.list <- list("ctrl.d1" = ctrl.d1, "ctrl.d2" = ctrl.d2,
                  "stim.d1" = stim.d1, "stim.d2" = stim.d2)

pbmc <- merge(ifnb.list[["ctrl.d1"]], y = c(ifnb.list[["ctrl.d2"]],
                                            ifnb.list[["stim.d1"]], ifnb.list[["stim.d2"]]), 
              add.cell.ids = c("ctrl.d1", "ctrl.d2",
                               "stim.d1", "stim.d2"), project = "pbmc")

# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
grep ("^CCL", rownames(pbmc[["RNA"]]),value = T)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-") # this dataset doesnt contain MT DNA, otherwise we subset on <10% MT

VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
#OUTPUT

FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
#OUTPUT`

**Comment by Dragonmasterx87** [comment]
Hi @Depraved-Dolphin 

Can you please tell me the output of `head(pbmc@meta.data)` as well as `sessionInfo()` thanks

**Comment by Dragonmasterx87** [comment]
Any updates on this?

**Comment by Depraved-Dolphin** [comment]
Hello @Dragonmasterx87 ,

Thank you for the attention to this issue. I was able to find the problem. I did not specify the metadata in the D1, D2 objects. Once I added the metadata, the integration was able to proceed.

**Comment by Dragonmasterx87** [comment]
> Hello @Dragonmasterx87 ,
> 
> Thank you for the attention to this issue. I was able to find the problem. I did not specify the metadata in the D1, D2 objects. Once I added the metadata, the integration was able to proceed.

Yes, thats why I was asking for head(pbmc@meta.data) that would have told me what kind of metadata you have in your object, and if a slot was present having the data you needed. R needs to be told which data belongs to what kind of individual/experiment etc, and it does that via the metadata slot. So always remember to allocate metadata information carefully.

I am closing this issue now as resolved, if you have other questions related to this you can still message within this thread (even when closed) if you have other questions please raise a new issue.

🐉
